"""
This file reads the output file generated by a static run of CONQUEST
which outputs atomic forces and stresses, and the Harris-Foulkes energy at the end of the file.

This is different from post-processing with ASE,
which is probably easier but requires that you had `IO.WriteOutToASEFile T` before running.
This file will be useful for runs done without any ASE at all.

This class may also work on output files generated from structural/atomic relaxations,
but only if `IO.Iprint 2` because by default,
detailed information is not printed out at the end of these runs
(and frankly, only the final structure is important anyways).

I also attach the force components to each atom, denoted by their atom number.
"""

import re
from itertools import islice
from collections import deque
import numpy as np
import conquest2a._types as c2at
from conquest2a.conquest import conquest_input, conquest_coordinates_processor, Atom


class read_static_output:
    def __init__(
        self, output_file: c2at.FILE_PATH, conquest_processor: conquest_coordinates_processor
    ) -> None:
        self.output_file = output_file
        self.conquest_processor = conquest_processor
        self.buffer: deque[str]
        self.harris_foulkes_energy: c2at.REAL_NUMBER = 0.0  # [Ha]
        self.dft_energy: c2at.REAL_NUMBER = 0.0  # [Ha]
        self.free_energy: c2at.REAL_NUMBER = 0.0  # [Ha]
        self.forces_buff: c2at.REAL_ARRAY = np.array([])  # [Ha/bohr]
        self.stresses: c2at.REAL_ARRAY = np.array([])  # [GPa]

        # Get quantities from below this line
        self.read_last_n_lines()
        self.get_free_energy()
        self.get_hf_energy()
        self.get_dft_energy()
        self.read_assign_forces()
        self.get_stresses()

    def read_last_n_lines(self) -> deque[str]:
        with open(self.output_file, "r", encoding="utf-8") as file:
            # 25 comes from misc lines + a line for warnings
            # Then a block is printed for the forces for each atom
            # And also 2 extra kines for the force header
            # New line +  3 lines for Harris-Foulkes+DFT+Ground state energies
            lines = deque(file, maxlen=25 + int(self.conquest_processor.natoms) + 5)
            self.buffer = lines
            for line in lines:
                line = line.strip()
            return lines  #

    def _get_quantity_from_lines(
        self, line_to_match: str, err_str: str
    ) -> list[str] | c2at.REAL_NUMBER:
        buffer_line: str = ""
        for line in self.buffer:
            if line_to_match in line:
                buffer_line = line
                break
        matches = re.findall(self.conquest_processor.re_float, buffer_line)
        if not matches:
            print(err_str)
            return np.inf
        return matches

    def get_free_energy(self) -> c2at.REAL_NUMBER:
        free_energy = self._get_quantity_from_lines(
            "| Free Energy as E-TS", "Did not find a free energy line."
        )
        self.free_energy = float(free_energy[0]) if isinstance(free_energy, list) else free_energy
        return self.free_energy

    def get_hf_energy(self) -> c2at.REAL_NUMBER:
        hf = self._get_quantity_from_lines(
            "|* Harris-Foulkes energy",
            "Did not find a Harris-Foulkes line.",
        )
        self.harris_foulkes_energy = float(hf[0]) if isinstance(hf, list) else hf
        return self.harris_foulkes_energy

    def get_dft_energy(self) -> c2at.REAL_NUMBER:
        dft = self._get_quantity_from_lines(
            "|* DFT total energy", "Did not find a DFT total energy line."
        )
        self.dft_energy = float(dft[0]) if isinstance(dft, list) else dft
        return self.dft_energy

    def read_assign_forces(self) -> None:
        header_index = 0
        for idx, line in enumerate(self.buffer):
            if "force:  Atom" in line:
                header_index = idx
                break
        temp = deque(
            islice(
                self.buffer,
                header_index + 1,
                header_index + int(self.conquest_processor.natoms) + 1,
            )
        )
        # print(temp)
        formatted_temp: list[str] = []
        for line in temp:
            formatted_temp.append(line.replace("force:", "").strip())
            # print(line)
        # print(formatted_temp)
        for line in formatted_temp:
            # At this point, every string is of the form "Atom number, force_x, force_y, force_z"
            # So just use regex matching again to assign everything
            # ASSUMES  THAT THE CORRECT COORDINATES FILE IS USED
            atom_number = int(re.findall(self.conquest_processor.re_index, line)[0])
            forces = np.array(re.findall(self.conquest_processor.re_float, line), dtype=np.float64)
            print(forces)
            # Rather than iterating through of list of atoms every time, take advantage of the fact
            # that conquest_processor.atoms is sorted by coordinate file order
            # which is preserved by CONQUEST after every run
            # so we simply assign index directly
            self.conquest_processor.atoms[atom_number - 1].forces = forces

    def get_max_force_atom(self) -> Atom:
        atom_with_max_force = self.conquest_processor.atoms[0]
        for atom in self.conquest_processor.atoms[1:]:
            if np.max(np.abs(atom.forces)) > np.max(np.abs(atom_with_max_force.forces)):
                atom_with_max_force = atom
        index = np.argmax(np.abs(atom_with_max_force.forces))
        direction = "x"
        if index == 1:
            direction = "y"
        elif index == 2:
            direction = "z"
        print(
            f"Atom {atom_with_max_force.number} has maximum force {np.max(np.abs(atom_with_max_force.forces))} [Ha/a0] in {direction} direction."
        )
        print(atom_with_max_force)
        return atom_with_max_force

    def get_stresses(self) -> None:
        stresses = self._get_quantity_from_lines(
            "force: Total stress:", "Unable to get total stresses"
        )
        if stresses != np.inf:
            self.stresses = np.array(stresses, dtype=np.float64)
        else:
            print("Stresses were not able to be located. Stress values have not been allocated.")


if __name__ == "__main__":
    conq_input = conquest_input({1: "O", 2: "Bi", 3: "Mn", 4: "Mn", 5: "Mn", 6: "Mn"})
    conq_proc = conquest_coordinates_processor("tests/data/test_output_input_coords.in", conq_input)
    output = read_static_output("tests/data/test_output.txt", conq_proc)

    print(output.conquest_processor.atoms)
    print(output.stresses)
    output.get_max_force_atom()
